<?php declare(strict_types=1);

namespace Sprain\Tests\SwissQrBill;

trait TraitValidQrBillsProvider
{
    protected bool $regenerateReferenceFiles = false;

    public static function validQrBillsProvider(): array
    {
        $creator = new QrBillTestDataRepository();

        return [
            ['qr-minimal-setup',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceQr'
                ])
            ],
            ['qr-payment-information-without-amount',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformationWithoutAmount',
                    'paymentReferenceQr'
                ])
            ],
            ['qr-payment-information-without-amount-but-debtor',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformationWithoutAmount',
                    'paymentReferenceQr',
                    'ultimateDebtor'
                ])
            ],
            ['qr-payment-information-without-amount-and-long-addresses',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditorLong',
                    'paymentAmountInformationWithoutAmount',
                    'paymentReferenceQr',
                    'ultimateDebtorLong'
                ])
            ],
            ['qr-payment-information-with-mediumlong-creditor-and-unknown-debtor',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditorMediumLong',
                    'paymentAmountInformationWithoutAmount',
                    'paymentReferenceQr'
                ])
            ],
            ['qr-payment-information-zero-amount',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformationZeroAmount',
                    'paymentReferenceQr',
                    'additionalInformationZeroPayment'
                ])
            ],
            ['qr-payment-reference-scor',
                $creator->createQrBill([
                    'header',
                    'creditorInformationIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceScor'
                ])
            ],
            ['qr-payment-reference-non',
                $creator->createQrBill([
                    'header',
                    'creditorInformationIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceNon'
                ])
            ],
            ['qr-ultimate-debtor',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceQr',
                    'ultimateDebtor'
                ])
            ],
            ['qr-special-chars-ultimate-debtor',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceQr',
                    'utf8SpecialCharsUltimateDebtor'
                ])
            ],
            ['qr-international-ultimate-debtor',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceQr',
                    'internationalUltimateDebtor'
                ])
            ],
            ['qr-additional-information',
                $creator->createQrBill([
                    'header',
                    'creditorInformationQrIban',
                    'creditor',
                    'paymentAmountInformation',
                    'paymentReferenceQr',
                    'additionalInformation'
                ])
            ],
            ['qr-full-set',
                $creator->getQrBillFullSet()
            ],
            ['qr-alternative-schemes',
                $creator->getQrBillWithAdditionalSchemes()
            ]
        ];
    }
}
